cmake_minimum_required(VERSION 3.12)
project(nmos-client)
set(CMAKE_BUILD_TYPE Debug)
include(CTest)
add_subdirectory(src)
if(BUILD_TESTING)
    add_subdirectory(tests)
endif()

if(UNIX)
    set(CPACK_GENERATOR "DEB")
    set(CPACK_PACKAGE_NAME "nmos-daemon")
    set(CPACK_PACKAGE_VERSION "1.0.0")
    set(CPACK_PACKAGE_CONTACT "nmos@example.com")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "NMOS Sync Daemon")
    set(CPACK_PACKAGING_INSTALL_PREFIX "/")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "nmos-daemon")
    set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "python3, iproute2")
    set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
        "${CMAKE_SOURCE_DIR}/packaging/postinst;${CMAKE_SOURCE_DIR}/packaging/prerm;${CMAKE_SOURCE_DIR}/packaging/postrm")
    include(CPack)
elseif(WIN32)
    set(CPACK_GENERATOR "ZIP")
    set(CPACK_PACKAGE_NAME "nmos-sync-daemon")
    set(CPACK_PACKAGE_VERSION "1.0.0")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "NMOS Sync Daemon (Portable)")
    set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)
    include(CPack)
endif()
